{
    'packet_timestamp': '1759356243520985', 
    'stage': 'NORMAL_FIRST_HALF_PRE', 
    'stage_time_left': '300000000', 
    'command': 'HALT', 
    'command_counter': 0, 
    'command_timestamp': '0', 
    'yellow': {
        'name': 'Unknown', 
        'score': 0, 
        'red_cards': 0, 
        'yellow_cards': 0, 
        'timeouts': 4, 
        'timeout_time': 300000000, 
        'goalkeeper': 0, 
        'foul_counter': 0, 
        'ball_placement_failures': 0, 
        'can_place_ball': True, 
        'max_allowed_bots': 11, 
        'bot_substitution_intent': False, 
        'ball_placement_failures_reached': False, 
        'bot_substitution_allowed': False, 
        'bot_substitutions_left': 5, 
        'bot_substitution_time_left': 0, 
        'hull_color': 'HULL_COLOR_LIGHT'
    }, 
    'blue': {
        'name': 'Unknown', 
        'score': 0, 
        'red_cards': 0, 
        'yellow_cards': 0, 
        'timeouts': 4, 
        'timeout_time': 300000000,
        'goalkeeper': 0, 
        'foul_counter': 0, 
        'ball_placement_failures': 0, 
        'can_place_ball': True, 
        'max_allowed_bots': 11, 
        'bot_substitution_intent': False, 
        'ball_placement_failures_reached': False, 
        'bot_substitution_allowed': False, 
        'bot_substitutions_left': 5, 
        'bot_substitution_time_left': 0, 
        'hull_color': 'HULL_COLOR_DARK'
    }, 
    'designated_position': {
        'x': 0.0, 
        'y': 0.0
    }, 
    'blue_team_on_positive_half': False, 
    'next_command': 'PREPARE_KICKOFF_YELLOW', 
    'current_action_time_remaining': '0', 
    'source_identifier': '09d31269-06ad-45fe-8aae-84b5583f1320', 
    'match_type': 'UNKNOWN_MATCH'
}